connectedin/urls.py
from django.contrib import admin
from django.urls import path
from perfis import views
from usuarios import views as view_usuario

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Principal
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    
    # auxiliar
    path('esqueciasenha/', views.esqueci_a_minha_senha, name='esqueci_senha'),

    # Perfil
    path('perfil/<int:perfil_id>/', views.exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar/',views.convidar, name='convidar'),
    path('perfil/<int:perfil_id>/desfazer/',views.desfazer_amizade, name='desfazer'),
    path('perfil/<int:convite_id>/aceitar/',views.aceitar, name='aceitar'),
    path('perfil/<int:convite_id>/rejeitar/',views.rejeitar, name='rejeitar'),
    path('encontrar/', views.buscar_usuario, name='buscar_usuario'),
    path('conexoes/', views.conexoes, name='conexoes'),
    path('alterarperfil/', views.alterar_perfil, name='alterar_perfil'),
    path('alterarcapa/', views.alterar_capa, name='alterar_capa'),
    path('alterarcor/', views.alterar_cor, name='alterar_cor'),
    #Perfil Postagem,
    path('postagem/', views.postagem, name='postagem'),
    path('deletepostagem/<int:id_postagem>', views.delete_postagem, name='delete_postagem'),
    path('minhaspostagem/', views.minhas_postagens, name='minhas_postagens'),
    path('excluirpostagem/<int:id_postagem>', views.excluir_postagem, name='excluir_postagem'),

    # Usuarios
    path('registrar/', view_usuario.RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', view_usuario.LoginUsuarioView.as_view(), name='login'),
    path('deslogar/', view_usuario.logout_view, name='deslogar'),
    path('alterarsenha/', view_usuario.AlterarSenhaView.as_view(), name='alterar_senha'),
    path('tornarsuperuser/<int:id_perfil>', view_usuario.tornar_superuser, name='tornar_superuser'),
    path('retirarsuperuser/<int:id_perfil>', view_usuario.retirar_superuser, name='retirar_superuser'),
    path('bloquearuser/<int:id_perfil>', view_usuario.bloquear_usuario, name='bloquear_user'),
    path('bloquearmeuuser/', view_usuario.bloquear_meu_usuario, name='bloquear_meu_user'),
    path('desbloquearuser/<int:id_perfil>', view_usuario.desbloquear_usuario, name='desbloquear_user'),

]

# Função para que o django mostre imagens durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor verifique os campos informados.')
            valid = False

        user_exists = User.objects.filter(username=self.cleaned_data['email']).exists()
        if user_exists:
            self.adiciona_erro('Usuário já cadastrado')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = None
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from usuarios.forms import RegistrarUsuarioForm
from perfis.models import Perfil
from django.contrib import messages

# Create your views here.
class RegistrarUsuarioView(View):
    template_name = 'usuarios/registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(username=dados_form['email'],
                                                email=dados_form['email'],
                                                password=dados_form['senha'])

            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)
            perfil.save()
            messages.add_message(request, messages.INFO, 'Usuário cadastrado com sucesso')
            return redirect('login')
        return render(request, self.template_name, {'form': form})


class LoginUsuarioView(View):
    template_name = 'usuarios/login.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get('user')
        password = request.POST.get('pass')

        user = authenticate(request, username=username, password=password)

        if user is None:
            if User.objects.filter(email=username):
                messages.add_message(request, messages.INFO, 'Usuário bloqueado.')
            else:
                messages.add_message(request, messages.INFO, 'Usuário não cadastrado.')
        else:
            login(request, user)
            return redirect('index')

        return redirect('login')


class AlterarSenhaView(View):
    template_name = 'usuarios/alterarsenha.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        senha_antiga = request.POST.get('senha_antiga')
        nova_senha = request.POST.get('nova_senha')
        repete_senha = request.POST.get('repete_senha')

        if self.dados_validos_para_alterar_senha(request, senha_antiga, nova_senha, repete_senha):
            user = request.user
            user.set_password(nova_senha)
            user.save()
            return redirect('deslogar')

        return redirect('alterar_senha')


    def dados_validos_para_alterar_senha(self, request, senha_antiga, nova_senha, repete_senha):
        valido = True
        username = request.user.username
        user = authenticate(request, username=username, password=senha_antiga)

        if user is None:
            messages.add_message(request, messages.INFO, 'senha não confere com a cadastrada')
            valido = False
        if nova_senha != repete_senha:
            messages.add_message(request, messages.INFO, 'senha repetida não confere')
            valido = False
        return valido


# Funções soltas
def logout_view(request):
    logout(request)
    return redirect('login')


def tornar_superuser(request, id_perfil):
    if request.user.is_superuser:
        user = Perfil.objects.get(id=id_perfil).usuario
        user.is_superuser = True
        user.save()
    return redirect('/perfil/{}/'.format(id_perfil))


def retirar_superuser(request, id_perfil):
    if request.user.is_superuser:
        user = Perfil.objects.get(id=id_perfil).usuario
        user.is_superuser = False
        user.save()
    return redirect('/perfil/{}/'.format(id_perfil))


def bloquear_usuario(request, id_perfil):
    if request.user.is_superuser:
        user = Perfil.objects.get(id=id_perfil).usuario
        user.is_active = False
        user.save()
    return redirect('/perfil/{}/'.format(id_perfil))


def bloquear_meu_usuario(request):
    user = request.user
    user.is_active = False
    user.save()
    return redirect('deslogar')


def desbloquear_usuario(request, id_perfil):
    if request.user.is_superuser:
        user = Perfil.objects.get(id=id_perfil).usuario
        user.is_active = True
        user.save()
    return redirect('/perfil/{}/'.format(id_perfil))

usuarios/templates/usuarios/alterarsenha.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static '/css/estilo.css' %}">
    <title>Alterar senha</title>
</head>

<body>
    <div class="container_alt_senha bg-dark">
        <div class="alterar_senha">
                {% if messages %}
                {% for message in messages %}
        
                <div class="alert alert-warning full-w">
                    {{message}}
                </div>
        
                {% endfor %}
                {% endif %}
        </div>

        <section class="card alterar_senha bg-warning">
            <div class="card-header text-white">
                <h2 class="text-center">Alterar a senha</h2>
            </div>
            <div class="card-body bg-light">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="senha_antiga">Senha antiga</label>
                        <input class="form-control" type="password" name="senha_antiga" id="senha_antiga"
                            placeholder="Digite a sua senha antiga">
                    </div>
                    <div class="form-group">
                        <label for="nova_senha">Nova senha</label>
                        <input class="form-control" type="password" name="nova_senha" id="nova_senha"
                            placeholder="Digite uma senha nova">
                    </div>
                    <div class="form-group">
                        <label for="repete_senha">Repete senha</label>
                        <input class="form-control" type="password" name="repete_senha" id="repete_senha"
                            placeholder="Digite a senha nova novamente">
                    </div>
                    <button type="submit" class="btn btn-info full-w">SALVAR</button>
                </form>
            </div>
        </section>
    </div>

</body>

</html>

usuarios/templates/usuarios/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Usuarios</title>
</head>
<body>

    {% block main %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    
</body>
</html>

usuarios/templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/estilo.css' %}">
    <style>
        h2{color: rgb(133, 201, 24);}
        h3{color: rgb(54, 187, 72);}
    </style>
</head>

<body>

    <main class="row mx-0 login bg-info" style="background: url({% static 'media/img/bg.jpg' %}); background-attachment: fixed; background-repeat: no-repeat; background-size: cover;">
        <section class="col col-md-8 descricao">
            <!-- <video src="{% static '/media/video/bg-login.webm' %}" autoplay="true" loop="true" id="background-media"></video> -->
            <div class="conteudo container">
                <h2>TodeZoio</h2>
                <h3>
                    Feito por estudantes, para estudantes.
                </h3>
            </div>
        </section>
        <aside class="col col-md-4 center-center form-login">

            {% if messages %}
            <div class="alertas">
                {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span
                            aria-hidden="true">&times;</span> </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="user">Login</label>
                    <input class="form-control" name="user" id="user" placeholder="user@example.com">
                </div>
                <div class="form-group mt-0">
                    <label for="pass">Senha</label>
                    <input class="form-control" type="password" name="pass" id="pass" placeholder="********">
                </div>
                <button class="btn btn-success full-w" type="submit">Entrar</button>
                <button type="button" class="btn btn-info mt-2 full-w" data-toggle="modal"
                    data-target="#cadastrar-usuario">Cadastrar</button>
            </form>
        </aside>
    </main>

    <!-- Modal -->
    <div class="modal fade" id="cadastrar-usuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Cadastrar novo usuário</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'registrar' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_nome">Nome</label>
                            <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *"
                                required>
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            <input type="email" id="id_email" name="email" class="form-control" placeholder="Email *"
                                required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="id_senha">Senha</label>
                            <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *"
                                required>
                        </div>

                        <hr />
                        <div class="form-group">
                            <label for="id_telefone">Telefone</label>
                            <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone"
                                required>
                            <label for="id_nome_empresa">Empresa</label>
                            <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa"
                                required>
                        </div>

                        <hr />
                        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

                        {% if form.errors %}
                        <div class="alert alert-danger">
                            <button class="close" data-dismiss="alert" arial-hiden="True">x</button>
                            {{ form.non_field_errors }}
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

usuarios/templates/usuarios/logina.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static '/css/estilo.css' %}">
    <title>TodeZoio - Login</title>
</head>

<body class="container bg-dark login-page">

    <main class="row">
        <section class="col col-sm-12 col-md-8 text-white center-center">
            <div class="container">
                <h1>ConnectedIn</h1>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum deleniti, nostrum soluta nobis
                    voluptas blanditiis eaque, labore quasi sed sequi commodi nihil animi illum. Autem sunt facere
                    aspernatur ducimus laborum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint saepe
                    placeat sit incidunt beatae explicabo fugiat? Tempora cumque et, recusandae repudiandae corporis
                    vero voluptas neque repellendus exercitationem placeat, beatae commodi.
                </p>
            </div>
        </section>
        <aside class="col col-sm-12 col-md-4 container-login bg-info text-white px-3">
            <div class="container">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="user">Login</label>
                        <input class="form-control" name="user" id="user"
                            placeholder="Digite o seu username">
                    </div>
                    <div class="form-group mt-0">
                        <label for="pass">Senha</label>
                        <input class="form-control" type="password" name="pass" id="pass"
                            placeholder="Digite a sua senha">
                    </div>
                    <button class="btn btn-warning text-white full-w" type="submit">ENTRAR</button><br>
                    <a class="btn btn-success text-white full-w" href="{% url 'registrar' %}">CADASTRAR</a><br>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-info mt-3" role="alert">
                            {{message}}
                            </dixv>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
        </aside>
    </main>


</body>

</html>

usuarios/templates/usuarios/registrar.html
{% extends 'usuarios/base.html' %}
{% load static %}

{% block main %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">

    <div class="container_alt_senha bg-dark">
        <div class="alterar_senha">
                {% if messages %}
                {% for message in messages %}
        
                <div class="alert alert-warning full-w">
                    {{message}}
                </div>
        
                {% endfor %}
                {% endif %}
        </div>

        <section class="card alterar_senha bg-warning">
            <div class="card-header text-white">
                <h2 class="form-signin-heading text-center">Crie seu usuário</h2>
            </div>
            <div class="card-body bg-light">
                <form class="form-signin" action="{% url 'registrar' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nome">Nome</label>
                        <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="email" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>
                    </div>
                    <div class="form-group">
                        <label for="id_senha">Senha</label>
                        <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>
                    </div>
                    
                    <hr />
                    <div class="form-group">
                        <label for="id_telefone">Telefone</label>
                        <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required>
                        <label for="id_nome_empresa">Empresa</label>
                        <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required>
                    </div>
            
                    <hr />
                    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <button class="close" data-dismiss="alert" arial-hiden="True">x</button>
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}
            
                </form>
            </div>
        </section>
    </div>

{% endblock %}